# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - maintenance
      - github_actions
    open-pull-requests-limit: 5
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
  - package-ecosystem: npm  # dev dependencies
    allow:
      - dependency-type: development
      - dependency-type: indirect
    directory: /
    labels:
      - changelog:skip
      - dependencies
      - javascript
    open-pull-requests-limit: 5
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
  - package-ecosystem: npm  # prod dependencies
    allow:
      - dependency-type: production
    directory: /
    labels:
      - dependencies
      - javascript
    open-pull-requests-limit: 5
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
  - package-ecosystem: pip  # dev dependencies
    allow:
      - dependency-type: development
      - dependency-type: indirect
    directory: /
    labels:
      - changelog:skip
      - dependencies
      - poetry
      - python
    open-pull-requests-limit: 10
    schedule:
      day: friday
      interval: weekly
      time: "07:30"
      timezone: America/New_York
  - package-ecosystem: pip  # prod dependencies
    allow:
      - dependency-type: production
    directory: /
    labels:
      - dependencies
      - poetry
      - python
    open-pull-requests-limit: 10
    schedule:
      day: monday
      interval: weekly
      time: "08:00"
      timezone: America/New_York
    versioning-strategy: lockfile-only
