---
language: python
addons:
  apt:
    packages:
      - pandoc
      - sed
python:
  - "2.7"
  # See setup.py for notes about pending Python 3 support
  # - "3.4"
  # - "3.5"
  # - "3.6"
install:
  - "pip install docopt flake8 flake8-docstrings pep8-naming future pylint \
     yamllint troposphere>=1.9.0 botocore>=1.6.0 boto3>=1.3.1 colorama~=0.3.7 \
     PyYAML~=3.12 awacs>=0.6.0 formic~=0.9b gitpython~=2.0 schematics~=2.0.1 \
     python-dateutil~=2.0"
script: make travis
