apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kiam-agent-tls
  namespace: kube-system
spec:
  secretName: kiam-agent-tls
  commonName: agent
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kiam-server-tls
  namespace: kube-system
spec:
  secretName: kiam-server-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "localhost"
    - "kiam-server"
  ipAddresses:
    - "127.0.0.1"
