---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  # nodeSelector:
  #   node-role.kubernetes.io/worker: "true"
  # selector:
  #   matchLabels:
  #     role: worker
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: k8s-ENV-pod-role-demo-app
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app-pod
        # image: mesosphere/aws-cli:1.14.5
        # command: [ "/bin/sh", "-c", "--" ]
        image: ubuntu
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
